name: CI/CD Pipeline for Iris Classification

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install DVC
        run: |
          pip install dvc

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Verify model outputs
        run: |
          test -f models/model.joblib || exit 1
          test -f models/scaler.joblib || exit 1
          echo "Model files verified successfully!"

      - name: Run model evaluation
        run: |
          python src/evaluate.py

  docker-build:
    runs-on: ubuntu-latest
    needs: test-and-validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t iris-classification:latest .

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p 5000:5000 iris-classification:latest
          sleep 10
          docker ps
          docker logs test-container
          docker stop test-container
          docker rm test-container
